### ISSUE TITLE
Disable Create New

### ISSUE THREAD

**Issue by amaster507** [koolamusic/chakra-ui-autocomplete#10]
For my one of my use cases, I do not want users to be able to create new options. Of course, by leaving out the `onCreateItem` prop, the newly created item does nothing, but it still shows to Create the new item. I don't want that at all for this use case

![image](https://user-images.githubusercontent.com/2472115/99699813-038d1b80-2a58-11eb-9e2e-110de83ea3d2.png)

**Comment by amaster507** [comment]
I believe this can be handled by modifying this line:

https://github.com/koolamusic/chakra-ui-autocomplete/blob/3e75e5124c4812e7d225356d618512f94b106177/src/index.tsx#L290

to:

```
{(isCreating && onCreateItem) ? (
```

**Comment by koolamusic** [comment]
so I'm thinking more like allow users to enable it as a prop if they want that option yeah?

**Comment by amaster507** [comment]
Isn't that basically what it does by providing or not providing the onCreateItem property which takes a function. If they provide that function then they want to allow created items. If they do not add that prop with a function, then they do not want to handle created items. So then the created items get thrown into the current items when created, but they do not exist in the original data.

**Comment by amaster507** [comment]
I see the merge was accepted. If this is acceptable and handles the problem then feel free to close this issue unless more discussion is needed around this topic.

**Comment by koolamusic** [comment]
Of course yeah, what I'd begin looking at is the pathway to work with `v1.0.0` so there would be more options for various multi-select types

**Comment by santiruffino** [comment]
Hey guys! I saw the PR to disable the create option, but I can't find how should I disable that option from the component. Do you have any examples to help me? Thanks

**Comment by koolamusic** [comment]
@santiruffino you basically have to not use the `onCreateItem` Prop, here is an example

```jsx
  <CUIAutoComplete
          label="Choose preferred work locations"
          placeholder="Type a Country"
          items={pickerItems}
          selectedItems={selectedItems}
          onSelectedItemsChange={(changes) =>
            handleSelectedItemsChange(changes.selectedItems)
          }
        />

```

In this snippet, we do not pass the `onCreateItem` which usually takes in a createItem handler `onCreateItem={handleCreateItem}`

By not adding it as a `prop` The Component knows not to use it

**Comment by santiruffino** [comment]
Great, thanks! One more question, I'm trying to use this component with an array that has ~500 items. But I'm not able to render my items. Could cause the number of items?

**Comment by koolamusic** [comment]
however I believe you can leverage the `itemRenderer` prop to define a memoized component to render your items, if anything `match-sorter` is used in the filter algorithm, i'll test this with something like `fuzzy-search` and see what the results are

**Comment by xencodes** [comment]
> @santiruffino you basically have to not use the `onCreateItem` Prop, here is an example
> 
> ```js
>   <CUIAutoComplete
>           label="Choose preferred work locations"
>           placeholder="Type a Country"
>           items={pickerItems}
>           selectedItems={selectedItems}
>           onSelectedItemsChange={(changes) =>
>             handleSelectedItemsChange(changes.selectedItems)
>           }
>         />
> ```
> 
> In this snippet, we do not pass the `onCreateItem` which usually takes in a createItem handler `onCreateItem={handleCreateItem}`
> 
> By not adding it as a `prop` The Component knows not to use it

![Screenshot 2021-06-22 at 07 49 02](https://user-images.githubusercontent.com/31907722/122852497-53a1c880-d32e-11eb-9b18-530bbf1de01d.png)


*I don't think it's working*

**Comment by seanyang0813** [comment]
@xencodes I was facing the same issue. After looking around, it seems like there is a new boolean prop for disableCreateItem in the merged pr here https://github.com/koolamusic/chakra-ui-autocomplete/pull/40
