### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by eric-hc** [koolamusic/chakra-ui-autocomplete#16]
Using version `1.2.0` with `@chakra-ui/react` version `1.0.1`, getting this compilation error:

```
wait  - compiling...
error - ./node_modules/chakra-ui-autocomplete/dist/chakra-ui-autocomplete.cjs.development.js:15:0
Module not found: Can't resolve '@chakra-ui/core'
null
```

I think this library needs to be updated for the latest Chakra release or I need to add `@chakra-ui/core` as a dep?

**Comment by koolamusic** [comment]
yes please,  **@chakra-ui/core** as a peer dependency and needs to be installed in the project where you'd be using this library
