### ISSUE TITLE
Customize item creation

### ISSUE THREAD

**Issue by aaneto** [koolamusic/chakra-ui-autocomplete#29]
Hello, everyone reading this :)

I have a feature request for the component, it would be useful for me to have these options:

- Disallow creating items
- Changing the text on the box previous to creation for internationalization.

I can code this into a PR, but first I'd like to know if these features are aligned with the vision of the maintainers and how they imagine this being implemented.

**Comment by aaneto** [comment]
Right now I'm doing `onCreateItem={() => null}` to ignore the item creation but it does not prevent the creation box to appear.

**Comment by koolamusic** [comment]
Yes @aaneto please feel free to send a PR. I for one am very keen on internationalization
