### ISSUE TITLE
Does not work with chakra-ui/core 1.0.0-rc.8

### ISSUE THREAD

**Issue by amaster507** [koolamusic/chakra-ui-autocomplete#5]
I received a compile error when trying to use this.

> Module not found. Can't resolve '@chakra-ui/core/dist/Box' in '[my-project-path]\node_modules\chakra-ui-autocomplete\dist'

I was really excited to start using this. Guess I will build out what we need in the meantime.

**Comment by koolamusic** [comment]
@amaster507 what version of chakra are you using?

**Comment by amaster507** [comment]
Thank you!
