### ISSUE TITLE
Making the item list scrollable

### ISSUE THREAD

**Issue by Gazimix** [koolamusic/chakra-ui-autocomplete#68]
First of all, this is an awesome addon.
Is there a way to make the Item List scrollable? When there are too many options, it begins to be cumbersome and would be a lot better if there was a way to limit how many items are shown in the list, with an option to choose the amount of items and when it becomes scrollable.
If there's any easy way to add this functionality, I think it would be useful!

**Comment by koolamusic** [comment]
in the Props documentation https://github.com/koolamusic/chakra-ui-autocomplete#props

You can style the lists using `listStyleProps` 
I think there could be a better way of handling this or 😕 
But `listStyleProps` should do it for you.
