### ISSUE TITLE
Missing Dependency react-highlight-words

### ISSUE THREAD

**Issue by amaster507** [koolamusic/chakra-ui-autocomplete#7]
> ./node_modules/chakra-ui-autocomplete/dist/chakra-ui-autocomplete.cjs.development.js
Module not found: Can't resolve 'react-highlight-words' in '[my-project-path]\node_modules\chakra-ui-autocomplete\dist'

I believe this needs to be added as a dependency. Just working through to get this working, and this was one error that occurred.

**Comment by d-ivashchuk** [comment]
Still experiencing this with `1.2.3`

**Comment by koolamusic** [comment]
oh wow, should not be.
